### ISSUE TITLE
Update Better Flame Particles version to 1.20.1

### ISSUE THREAD

**Issue by Therkelsen** [Therkelsen/echoes_of_the_wilderness#2]
Better Flame Particles 1.20.1 version is currently made for 1.19, so it complains about a version mismatch.

[Curse Forge page](https://www.curseforge.com/minecraft/texture-packs/better-flame-particles)

![image](https://github.com/Therkelsen/echoes_of_the_wilderness/assets/37107686/da77403d-4327-4f3e-a3f8-bd0dad502bd9)
![image](https://github.com/Therkelsen/echoes_of_the_wilderness/assets/37107686/3ca2c380-b0c2-4df9-ad92-6f2d01346cf2)

**Comment by Tschipcraft** [comment]
Updated the file on Curse Forge 👍
Thanks for using my project in the modpack 🎉

**Comment by Therkelsen** [comment]
Great, thank you for the update!
