### ISSUE TITLE
Update Fadeless to 1.20.1

### ISSUE THREAD

**Issue by Therkelsen** [Therkelsen/echoes_of_the_wilderness#8]
Currently, the mod is made for 1.20-Snapshot, and not 1.20.1.

Update to 1.20.1, when the update comes out.

[Curse Forge Page](https://www.curseforge.com/minecraft/mc-mods/fadeless)

**Comment by DerpDerpling** [comment]
It works fine on 1.20.1, no update is required. Another mod it works well together with is [remove reloading screen](https://www.curseforge.com/minecraft/mc-mods/rrls/files) , which removes the resource pack reloading screen.

**Comment by Therkelsen** [comment]
Great, I just noticed that it wasn't specifically for 1.20.1, so I figured that might cause issues.

Also yeah, that mod is also part of the pack :D
